name: 'Constable Analyze'
description: 'Run Constable Analyze'
inputs:
  constable-api-key: 
    description: 'Your constable API Key'
    required: true
  terraform-module-root: 
    description: 'root of the terraform file'
    required: true
  aws-access-key-id: 
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key: 
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  github-ref:
    description: "Pass the GITHUB_REF environment variable"
    required: true
  github-repository:
    description: "Pass the GITHUB_REPOSITORY environment variable"
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bigbadwolfsecurity/brickhouse/cli:v0.0.9-alpha.0ea2bb01'
  args:
    - analyze
    - ${{ inputs.terraform-module-root }}
    - --force
    - --api_key
    - ${{ inputs.constable-api-key }}
    - --github_ref
    - ${{ inputs.github-ref }}
    - --github_repository
    - ${{ inputs.github-repository }}
  env: 
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}