name: 'Constable Analyze'
description: 'Run Constable Analyze'
inputs:
  terraform-module-root: 
    description: 'root of the terraform file'
    required: true
  aws-access-key-id: 
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key: 
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bigbadwolfsecurity/brickhouse/cli:latest'
  args:
    - analyze
    - ${{ inputs.terraform-module-root }}
    - --force
    - --github_ref
    - ${{ env.GITHUB_REF }}
    - --github_repository
    - ${{ env.GITHUB_REPOSITORY }}
  env: 
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}